
import os

# 默认配置
FIN_DAILY_ENABLED = os.getenv("FINANCE_DAILY_ENABLED", "1") == "1"
FIN_DAILY_MARKET = "CN_A"
FIN_DAILY_DATA_PROVIDER = os.getenv("FINANCE_DAILY_DATA_PROVIDER", "eastmoney")
FIN_DAILY_RUN_HOUR = int(os.getenv("FINANCE_DAILY_HOUR", "15"))
FIN_DAILY_RUN_MINUTE = int(os.getenv("FINANCE_DAILY_MINUTE", "35"))
FIN_DAILY_LLM_CONCURRENCY = int(os.getenv("FINANCE_DAILY_LLM_CONCURRENCY", "1"))
FIN_DAILY_PROMPT_VERSION = "v3_girlfriend"
FIN_DAILY_NEW_LIST_DAYS = 365
FIN_DAILY_AMOUNT_MIN = 100_000_000 # 1亿
FIN_DAILY_TOP_N = 3
FIN_DAILY_ANN_LOOKBACK_DAYS = 5
FIN_DAILY_EASTMONEY_PROXY = os.getenv("FINANCE_DAILY_EASTMONEY_PROXY", "")
FIN_DAILY_OUTPUT_MODE = "xiao_a"
FIN_DAILY_CHAT_PER_STOCK = True
FIN_DAILY_OVERVIEW_ENABLED = True
FIN_DAILY_ITEM_MAX_CHARS = 300
FIN_DAILY_SEND_INTERVAL_SECONDS = 1.0

TUSHARE_TOKEN = os.getenv("TUSHARE_TOKEN", "")
